flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- cairo-0.13.4.2
- glib-0.13.5.0
- gtk2hs-buildtools-0.13.3.1
- hashable-1.2.6.1
- hashtables-1.2.2.1
- mtl-2.2.1
- pango-0.13.4.0
- primitive-0.6.1.0
- random-1.1
- text-1.2.2.2
- utf8-string-1.0.1.1
- vector-0.12.0.1
- xml-1.3.14
resolver: ghc-8.0
